KNX-IOT/KNX-IOT-STACK

pythonbinding/oc_python.h
Fixes https://github.com/KNX-IOT/KNX-IOT-STACK/issues/239
=> Corrected python API doxygen comments

.github/workflows/cmake-linux.yml, .github/workflows/cmake-windows.yml, CMakeLists.txt, apps/testserver_all.c
Opening the PR now so that I can look at the actual errors on CI
=> enable warnings as errors

api/oc_core_res.c, include/oc_core_res.h, tools/doxygen.ini
=> removed unused code

apps/LSAB_minimal_all.c, apps/LSSB_minimal_all.c, include/oc_api.h, tools/doxygen.ini
- new main page title
- adding examples
=> doxygen update

api/oc_device_mode.c, api/oc_knx_dev.c, api/oc_knx_dev.h, api/oc_knx_sec.c, apps/testclient_all.c, apps/testserver_all.c, include/oc_core_res.h, include/oc_programming_mode.h, include/oc_ri.h, pythonbinding/tests/knx_test_sequence.py
added resources:
- dev/port
- dev/sa
- dev/da
=> added resources:

api/oc_discovery.c, api/oc_knx_fb.c
fix for url of instance
added dev/sa and dev/da on discovery response of :ia.
=> fix for url of instance

api/oc_buffer.c, api/oc_endpoint.c, api/oc_knx.c, api/oc_knx_client.c, api/oc_knx_client.h, api/oc_ri.c, api/oc_server_api.c, apps/simpleclient_spake_all.c, include/oc_buffer.h, include/oc_endpoint.h, messaging/coap/engine.c, messaging/coap/oscore.h, port/linux/ipadapter.c, port/linux/tcpadapter.c, port/oc_connectivity.h, port/windows/ipadapter.c, pythonbinding/oc_python.c, pythonbinding/oc_python.h, security/oc_oscore_context.c, security/oc_oscore_context.h, security/oc_oscore_engine.c, security/oc_spake2plus.c, security/oc_spake2plus.h, util/oc_process.c
adding device_index & group_index to endpoint
=> oscore changes

api/oc_knx_sec.c, pythonbinding/application_scripts/README.md, pythonbinding/application_scripts/install_config.py, pythonbinding/application_scripts/programming_mode.py, pythonbinding/application_scripts/test_server_config.json
=> adding security in python programs

CMakeLists.txt, api/oc_core_res.c, api/oc_knx_fp.c, api/oc_knx_fp.h, api/oc_ri.c, include/oc_ri.h, messaging/coap/coap.c
if(MSVC)
add_definitions(-D_CRT_SECURE_NO_WARNINGS)
endif()
=> documentation improvement & compile definition

api/oc_buffer.c, api/oc_ri.c
remove NULL assignment in message for deallocated pool.
=> change in refcount e.g. using function

api/oc_core_res.c, api/oc_knx_client.c, api/oc_knx_fp.c, api/oc_knx_fp.h, apps/lsab_minimal_all.c, apps/lssb_minimal_all.c, apps/testserver_all.c, include/oc_core_res.h, include/oc_ri.h
adding 4 new functions to set data directly on the ETS
=> work on ets

apps/testserver_all.c, messaging/coap/engine.c
- not sending echo message if incomming message is from myself.
=> fixes for oscore security

api/oc_knx_fp.c
fix for
Successful POST requests to the Group Object Table cause a Bad Request Response #74
=> add missing return

api/oc_knx.c, port/linux/dns-sd.c, port/linux/ipadapter.c, port/linux/ipadapter.h, port/windows/dns-sd.c, port/windows/ipadapter.c, port/windows/ipadapter.h
- Advertise the port used for unicast communications
- Update sevice when IA or IID are changed
=> Fixes for DNS-SD

api/oc_knx_client.c, api/oc_knx_client.h, api/oc_knx_dev.c, api/oc_knx_fp.c, api/oc_knx_fp.h, apps/testserver_all.c, include/oc_core_res.h
change ga from int to unsigned int
change grpid from int to unsigned int
change iid from int to int64
change fid from int to int64
=> size fixes for tables

api/oc_knx.c, api/oc_knx_fp.c, include/oc_knx.h
fixes for returning last received group command
=> fixes for group object table

CMakeLists.txt, api/oc_knx_sec.c, port/windows/storage.c
and enable OC_USE_STORAGE by default
=> reverse the NO_STORAGE to OC_USE_STORAGE

api/oc_knx.c, api/oc_knx_dev.c, api/oc_knx_fp.c, api/oc_knx_sec.c, api/oc_knx_swu.c, api/oc_server_api.c, include/oc_api.h
added the functions to the delete functions
=> rename function for no payload in return

api/oc_knx_swu.c, api/oc_knx_swu.h, apps/lsab_minimal_all.c, apps/lssb_minimal_all.c, apps/testserver_all.c
1- testserver_all now writes bytes received to a file
2- put handler now uses separate/delayed response
3- Added code to parse pkgs attribute (containing full binary size)
=> Some additions and changes for OTA upgrade

api/oc_knx_dev.c, api/oc_main.c, api/oc_main.h, include/oc_api.h
=> Added app-specific callback for programming mode

api/oc_client_api.c, api/oc_ri.c, messaging/coap/engine.c, messaging/coap/transactions.c, security/oc_oscore_engine.c
Reverts KNX-IOT/KNX-IOT-STACK#528
=> Revert "Fixes for Echos in multicast communication"

api/oc_knx.c
=> Fixes issue with feedback not being sent.

api/oc_core_res.c, api/oc_knx_gm.c
=> creation of the iot_router_resources

api/oc_knx.c, api/oc_knx_client.c, api/oc_knx_client.h
only needed when the device is running on the same PC
=> introduction of new ifdef for using multicast scope 2

api/oc_knx_fp.c
- fp/g/x
- fp/r/x
- fp/p/x
fix for crash reported on 145
=> fix check if entry is valid on GET of

api/oc_knx_dev.c
=> update for dev/sa /dev/da

CMakeLists.txt, api/oc_helpers.c, api/oc_knx_fp.c, api/oc_knx_helpers.c, api/oc_knx_helpers.h, api/oc_server_api.c, include/oc_api.h, include/oc_helpers.h
implementation in
/fp/g
/fp/r
/fp/p
page size is total size of the array
=> infrastructure of handling ?l=ps;l=total query parameters

api/oc_knx_gm.c, api/oc_knx_sec.c
query l=ps;ps
for auth/at and fp/gm
=> query l=ps;ps  for auth/at and fp/gm

api/oc_knx_fb.c, api/oc_knx_gm.c, api/oc_knx_sec.c
=> l=ps;l=total implementations for

api/oc_knx_dev.c, api/oc_knx_fp.c, include/oc_core_res.h, include/oc_ri.h, port/linux/ipadapter.c, port/oc_connectivity.h, port/windows/ipadapter.c
applied dev/mport for multicast group messaging.
=> implementation of /dev/mport

api/oc_core_res.c, api/oc_helpers.c, api/oc_knx_fp.c, api/oc_knx_fp.h, include/oc_core_res.h
- Helper to print uint64_t
- Functions to print reduced version of group recipient and publisher tables
=> Adds functions to facilitate printing of iid and group tables.

.github/workflows/cmake-linux.yml, api/oc_core_res.c, api/oc_discovery.c, api/oc_helpers.c, api/oc_knx_fp.c, api/unittest/apitest.cpp, include/oc_helpers.h
Bug fix due to inability failing snprintf with uint64_t on embedded:
- Added ability to convert from uint64_t to hex string representation on embedded
- Generalized uint64 printing function to print either decimal or hexadecimal representation of uint64_t
- Added unit tests for conversion from uint64_t to dec or hex
=> Bug fix + helper improvements + testing for embedded uint64_t

api/oc_rep.c
I thought i'd removed all of them. I need to be a bit more careful going forward
=> removed unnecessary printf used for debugging.

api/oc_knx.c, include/oc_ri.h
=> add /g next to .knx

CMakeLists.txt, api/oc_helpers.c, api/oc_knx_sec.c, api/oc_knx_sec.h, api/oc_replay.c, api/oc_replay.h, api/unittest/CMakeLists.txt, api/unittest/replaytest.cpp, include/oc_helpers.h
Not connected to the actual comms code that will be using this yet, but it's in a good place to be reviewed right now.
=> Implement SSN tracking, for use within replay protection

api/oc_replay.c
Made this change yesterday but somehow it wasn't added
=> add license to oc_replay.c

api/oc_core_res.c, api/oc_discovery.c, api/oc_knx.c, api/oc_knx_client.c, api/oc_knx_dev.c, api/oc_knx_fb.c, api/oc_knx_fp.c, api/oc_knx_gm.c, api/oc_knx_p.c, api/oc_knx_sec.c, api/oc_knx_sec.h, api/oc_knx_swu.c, api/oc_ri.c, api/oc_server_api.c, include/oc_core_res.h, include/oc_discovery.h, include/oc_helpers.h, include/oc_ri.h, messaging/coap/observe.c, messaging/coap/observe.h, util/oc_list.c, util/oc_list.h
Support const oc_resource_t stored in flash rather than heap.
=> Skyler const oc resource

api/oc_knx_fp.c
=> Fix fp/r entry delete

api/oc_knx_fp.c, include/oc_ri.h
Reverts KNX-IOT/KNX-IOT-STACK#728
=> Revert "Frank eitt fix"

api/oc_knx_fp.c, include/oc_ri.h
Reverts KNX-IOT/KNX-IOT-STACK#729
=> Revert "Revert "Frank eitt fix""

api/oc_knx.c
Bug was found when testing the "read on init" mechanism, which was failing due to a device thinking this message hasn't originated from itself, simply because the IP address didn't match the one of endpoint 0.
=> Fix how a msg is determined to be from self or not
