pythonbinding/knx_stack.py
pythonbinding/oc_python.c

The `resource` mutex in `knx_stack.py` was locked but never released, so I have removed it.
This PR initializes the Linux mutexes in the same place where the Windows ones are initialized. It also removes the mutex around `oc_main_poll();` within `func_event_thread` - this makes consecutive calls work on Linux. The client is also protected by a mutex within Python, so it should be sound, but I am not 100% sure...

Fix concurrency on Linux

---

security/oc_spake2plus.c
security/oc_spake2plus.h

Adds the `oc_gen_masterkey` which uses a securely seeded PRNG to generate masterkeys suitable for OSCORE encryption.

API for generating OSCORE masterkeys

---

api/oc_knx_fp.h

@WAvdBeek this fixes a build issue in the SDK - I'm just gonna merge it once CI passes since you're away.

add missing headers to oc_knx_fp.h

---

api/oc_knx_sec.c
api/oc_server_api.c

This PR addresses a couple issues identified by Valgrind while running knx_iot_virtual_sa:
- the lengths in certain access token strings were incorrect
- 8 bytes of memory were lost
Note that the last error is still taking place, though I think it should be gone... @WAvdBeek can you check that my changes to `oc_resource_bind_dpt` make sense?

Valgrind fixes

---

security/oc_oscore_engine.c

Turns out there are some circumstances under which secure multicasts are received, but the corresponding OSCORE context is not found. We do not want to respond to secure multicasts either way, and we arle already inside of an OSCORE function, so we do not need to check whether we have an OSCORE context before dropping the frame.

always drop responses to secure multicasts, regardless of oscore context

---

api/oc_client_api.c
api/oc_ri.c
messaging/coap/engine.c
messaging/coap/transactions.c
security/oc_oscore_engine.c

This pull request should fix [Luca's persistence issue](https://github.com/KNX-IOT/knx-iot-point-api-config/issues/47), though it is still WIP and a little bit unstable.
It adds a missing group address to the endpoint so that it can be used by higher level code. Right now this is done in a simplified way - the correct approach would be to use `oc_oscore_find_context_by_kid` to get the index of the auth table that was used to generate the context, and then obtain the actual group address by querying the auth table entry with said index.
It also enables transactions for S-mode messages, so that the Echo retransmissions can take place. Right now, the transactions on the client (push button) aren't really freed when they should be, so there is likely a memory leak. The correct behaviour would …

Fixes for Echos in multicast communication

---

messaging/coap/constants.h

A CoAP response timeout lets Thread devices sleeping with a period of 5 seconds to successfully complete the Spake handshake without excessive retransmissions.

increase CoAP timeout and adjust relevant constants

---

port/linux/dns-sd.c
port/windows/dns-sd.c

Passed the wrong buffer size, causing only the first digit of the port to be advertised.

correct port advertised by MDNS

---

messaging/coap/coap.c
messaging/coap/separate.c

Most of the code for this feature was already there: the correct token is being tracked, but it was not copied into the `coap_pkt` data structure which is serialized for the response. There was a minor bug in the serialization code too, which this PR also fixes.

Include token within ACKs that accept separate responses

---

include/oc_endpoint.h

Pre-emptively fixes a bug we would see with the (new) embedded build

remove structure size modification based on OC_OSCORE

---

api/oc_knx_sec.c

osc:id and osc:contextid are truncating final character, e.g.
When trying to enrol a device with serial number `sn:00FA1001230000`, the following happens:
```
Rx: oc_oscore_set_auth sn:00FA1001230000 ci:00FA1001230000
Rx:   at index: 0
Rx:     id (0)        : 00FA1001230000
Rx:     scope (9)     : 2144
Rx:     profile (38)  : 2 (coap_oscore)
Rx:     osc:id        : 00FA100123000
Rx:     osc:ms        : 1963e418c8e5fed6eb8fcb44b5059b54
Rx:     osc:contextid : 00FA100123000
Rx: -----oc_oscore_add_context---00FA100123000

Fixes bad length for osc.id and contextid

---

api/oc_rep.c

destructuring parsed objects/arrays into top level without freeing parent oc_rep_t left memory leak. This has been cleaned up now.

CBOR object/array memory leak

---

api/oc_knx.c
api/oc_knx_client.c

S-mode messages should use handler user-data specified, rather than fixed NULL or inherited from `/.knx` handler.

Fix handler contexts for S-Mode messages

---

api/oc_discovery.c
api/oc_knx.c
api/oc_knx_client.c
api/oc_knx_fp.c
api/oc_knx_fp.h
api/oc_knx_sec.c
api/oc_knx_sec.h
apps/simpleclient_spake_all.c
security/oc_oscore.h
security/oc_oscore_context.c
security/oc_oscore_engine.c

- get rid of receiver id in auth/at entry handlers
- get rid of serial number use in oscore ids
- add at field to publisher and recipient table
- make ID field in spake handlers text string instead of byte string

Security changes for spec 1.1

---

include/oc_helpers.h

casts were leaving data in ram. They've now been converted to const casts to keep everything in flash that should be there.

oc helpers cast to const to force out of .data

---

api/oc_buffer.c
api/oc_knx_sec.h
api/oc_replay.c
api/oc_replay.h
apps/simpleclient_spake_all.c
messaging/coap/engine.c
port/linux/oc_config.h
port/oc_connectivity.h
port/oc_log.h
port/windows/oc_config.h
security/oc_oscore_engine.c

We couldn't do replay protection for NON requests before because the retransmission code for CON frames was piggybacking off of the pre-existing transactions, which already cached requests in case they were not acknowledged. NON frames used to be freed right after sending.
This pull request adds APIs for 'soft references' to `oc_message_t` - messages that only have a soft ref in their reference count are freed if & only if no other buffers are available. This API is used to hang onto NON frames in case a Echo challenge comes through which requires retransmitting the request.
I think it should be possible to use the new mechanism for CON frames as well without any real tradeoffs - this would get rid of the duplicated code in `oc_engine.c`

Implement replay protection for NON frames

---

api/oc_knx_sec.c
api/oc_knx_sec.h
port/windows/oc_config.h
security/oc_oscore_context.c
security/oc_oscore_context.h
security/oc_oscore_engine.c

This PR lets the stack create recipient contexts dynamically, using the key ID & master secret from the auth/at entry, but taking the context ID from received requests.
Since we cannot store the security context for every sender in memory (we may have hundreds of them) this PR implements a Least Recently Used cache for recipient contexts only. Infrequently used contexts will be freed to make room for more useful ones. This has the advantage of not requiring extra flash / ram when talking to multiple recipients, the amount used is constant.
Tested with the spake test client in the stack, with and without a contextid in the request. Will do a bit more testing and mark as ready for review.

Generate recipient contexts dynamically using context ID of requests

---

api/oc_ri.c
include/oc_endpoint.h
messaging/coap/coap.c
messaging/coap/engine.c
messaging/coap/separate.c
security/oc_oscore_context.c
security/oc_oscore_engine.c

This pull request fixes a security vulnerability that allows an attacker to decrypt the start of the plaintext of every single OSCORE encrypted separate response.
This is a capture of the stack using separate responses alongside OSCORE encryption. The messages with no key ID & repeated Partial IVs end up reusing the AEAD nonce. Since they are consecutive & the first message is very predictable (it is always an empty ACK) this is much easier to exploit than the nonce reuse attacks from before we started using context IDs.
The screenshot actually shows older stack behaviour (from before #700 was merged). In the current stack the PIV is not included within separate responses, and the messages actually cannot be decrypted as the correct cached PIV can't be identified without a token (which …

Fix vulnerability in separate responses due to nonce reuse

---

api/oc_knx_dev.c
api/oc_knx_p.c

From spec: "Device hostname for DNS resolution (minimum 60 and maximum 253 characters according to [RFC1035] clause 2.3.4)."
But, from [RFC1035] clause 2.3.4: "names: 255 octets or less."
So spec needs to be updated?
yes, this was discussed on 27/10/2023

Fix hostname length

---

api/oc_rep.c

This is why the s-mode test is crashing: malloc inside oc_print_rep_as_json causes heap overflow

Stop rep printing without OC_PRINT

---

api/oc_core_res.c
api/oc_discovery.c
api/oc_knx.c
api/oc_knx_dev.c
api/oc_knx_fb.c
api/oc_knx_fp.c
api/oc_knx_gm.c
api/oc_knx_p.c
api/oc_knx_sec.c
api/oc_knx_swu.c
api/oc_ri.c
api/oc_server_api.c
apps/lsab_minimal_all.c
apps/lssb_minimal_all.c
apps/testserver_all.c
include/oc_api.h
messaging/coap/coap.c
tests/itc/ri/helper/RIHelper.cpp

Main changes:
1. Stop setting content format for responses with empty payload
2. Fix /p redirecting mechanism
3. In coap receiver: check payload length before checking content format
4. (According to recent spec changes) For multicast discoveries, only include ep in response payload

Frank eitt fix

---

api/oc_buffer.c
include/oc_buffer.h

Adds the `oc_buffer_num_free_incoming` and `oc_buffer_num_free_outgoing` functions which can be used to determine whether it is safe to send or receive a KNX-IoT packet.

add api for number of free buffers

---

api/oc_discovery.c

For testcases 5.1.1.4b, 5.1.1.4c, 5.1.1.4d, 5.1.1.7g

Change return status to allow empty linkformat responses

---

api/oc_knx.c
api/oc_knx_p.c
api/oc_ri.c
api/oc_server_api.c
include/oc_ri.h

The content format changes don't tolerate the response buffer being null, and the stack was hardfaulting when dereferencing the null pointer. The response buffer shouldn't be null for /k & /p redirects in the first place, but these checks are less risky than modifying the S-mode redirection right now.

check for null in send response functions

---

api/oc_knx_fb.c
api/oc_knx_sec.c

1. Functional blocks in e.g. discovery response now have interfaces if.ll, e.g. </f/00421_01>;rt=":fb.421";if=":if.ll";ct=40
2. Allow GET for if.i resources for metadata query parameter "m"

Fix various device responses, allow GET on if.i resources

---

api/oc_discovery.c
api/oc_knx_fp.c

1. For link-format requests: Set response content format to link-format if code is 2.0x but list is empty;
2. Ignore discovery request with non-existent ga;
3. Add missing "/" prefix in response;
4. Delete handlers for /fp/p/* & /fp/r/* weren't actually deleting. They were just setting the id of the entry to 0...
5. Delete requests with non-existent entry now returns error for /fp/g/*, /fp/p/* & /fp/r/*;

Various fixes for passing EITT tests

---

api/oc_discovery.c
api/oc_knx_dev.c
include/oc_ri.h

1. Return empty response for unicast discovery with g.s query
2. Stop allowing PUT to /dev/port (was handling it but doing nothing in handler)
3. Remove old /dev/ia resource

EITT fixes

---

api/oc_knx_dev.c
api/oc_knx_gm.c

erase functions for iot router:

---

CMakeLists.txt
api/oc_knx_client.c
security/oc_oscore_engine.c

Previously all non-confirmable messages sent out by the device are considered requests, but they can be responses. This, combined with enabling the replay protection, caused ETS download to fail.
e.g. When ETS sends a NON request using a new unsynchronised access token, the device should send a non-confirmable RESPONSE with 4.01 + echo; But before the fix, it's sending a non-confirmable REQUEST with 4.01 + echo, which ETS cannot handle
Also a fix so that IPV6 multicast destination addresses are created using the recipient GRPID instead of publisher

Fix for non-confirmable responses

---

CMakeLists.txt
api/oc_knx_client.c
api/oc_replay.c
api/oc_replay.h
api/unittest/replaytest.cpp
messaging/coap/engine.c

From Spec:
KNX IoT devices MAY trust the first authenticated multicast message from an unsynchronized peer by default, which is configurable

Allow first multicast msg from unsynchronised client

---

port/oc_storage.h

I had to look at the implementation of that function to figure out that it does nothing on embedded. Ideally this should be made clear in the API description in the header file

Clarification comment for storage api

---

CMakeLists.txt

If you are building locally, you will need to delete your build directory & run the build script again in order for this change to take effect.
If you are using binaries from CI, re-run CI to ensure the binaries use the stack after this PR was merged.

Disable replay protection

---

port/linux/ipadapter.c

These messages can only receive answers from within the Thread network, whereas an Unique Local Address, which is also sent, can be responded to from within and from outside of the Thread network.
Consequently, this PR drastically cuts down the number of IPv6 multicasts issued for every s-mode message, as there are 4 or so Thread-only addresses.

do not send multicast message using thread-only source addresses

---

CMakeLists.txt

Port is built by default (as usual) but it can be disabled by the CMake Cache, or by an external CMakeLists.txt.

cmake option for disabling the port

---

api/oc_knx_client.c
api/oc_knx_fp.c
api/oc_knx_sec.c
security/oc_oscore_context.c
security/oc_oscore_context.h
security/oc_oscore_engine.c

Implemented salt for fp/r entries.
Fixed client broker request query format (ep=knx://ia.<iid>.<ia>). iid & ia were included in decimal, but they need to be in hex.
Also fixed a bug with group address not getting freed when deleting an auth/at entry.

Salt implementation
